# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# WireGuard wg-easy #######################################
# #########################################################
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: WireGuard-VPN
    environment:
      - LANG=en
      - WG_HOST=${HOST_DOMAIN}
      - WG_PORT=51820
      - PASSWORD_HASH=${PASSWORD_HASH}
      - UI_CHART_TYPE=0
    volumes:
      - ./wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: '1'
      net.ipv4.ip_forward: '1'
    # depends_on:
    #   - adguard
    networks:
      wireguard:
        ipv4_address: 10.42.42.42
    restart: unless-stopped

# =========================================================
# Networks ================================================
# =========================================================
networks:
  wireguard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24

# =========================================================
# Volumes =================================================
# =========================================================

