# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# Jenkins #################################################
# #########################################################
  jenkins:
    container_name: Jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    volumes:
      - jenkins_home:/var/jenkins_home
  
# #########################################################
# SSH Agent #################################################
# #########################################################
  ssh-agent:
    container_name: Jenkins_SSH_Agent
    image: jenkins/ssh-agent

# =========================================================
# Networks ================================================
# =========================================================


# =========================================================
# Volumes =================================================
# =========================================================
volumes:
  jenkins_home:
