services:
  jenkins-agent1:
    container_name: jenkins-agent1
    image: jenkins/inbound-agent:latest
    restart: unless-stopped
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_AGENT_SECRET=${JENKINS_AGENT_SECRET}
    volumes:
      - ${HOST_JENKINS_AGENT}:/home/jenkins/agent
