DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
LogSyslog no

LogTime yes
LogVerbose no
MaxScanSize 500M
MaxFileSize 100M
MaxRecursion 16
MaxFiles 10000
