# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# Portainer ###############################################
# #########################################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    mem_limit: 256m
    environment:
      TZ: Europe/Zurich
    ports:
      - "9443:9443"   # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - traefik_proxy
# =========================================================
# Volumes =================================================
# =========================================================
volumes:
  portainer_data:
# =========================================================
# Networks ================================================
# =========================================================
networks:
  traefik_proxy:
    external: true