# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# Portainer ###############################################
# #########################################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      TZ: Europe/Zurich
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      # - 8000:8000
      - 9443:9443
    restart: always
# =========================================================
# Volumes =================================================
# =========================================================
volumes:
  portainer_data: