# =========================================================
# Services ================================================
# =========================================================
services:

# #########################################################
# Audiobookshelf ##########################################
# #########################################################
  audiobookshelf:
    container_name: audiobookshelf
    hostname: audiobookshelf
    mem_limit: 512m
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - /mnt/seagate-black/library/audiobooks:/audiobooks
      - /mnt/seagate-black/library/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - traefik_proxy

# =========================================================
# Networks ================================================
# =========================================================
networks:
  traefik_proxy:
    external: true


# =========================================================
# Volumes =================================================
# =========================================================

