[global]
   deadtime = 15
   min protocol = SMB2
   vfs objects = catia fruit streams_xattr
   kernel change notify = no
   stat cache = yes

[mouse]
   path = /share
   browsable = true
   read only = false
   guest ok = false
   veto files = /.apdisk/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   valid users = mouse

