# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# NAME ####################################################
# #########################################################
  sample:
    image: sample/image:latest

# =========================================================
# Networks ================================================
# =========================================================


# =========================================================
# Volumes =================================================
# =========================================================

