api:
  dashboard: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: {}
  file:
    directory: /etc/traefik/config
    watch: true
