# =========================================================
# Services ================================================
# =========================================================
services:

# #########################################################
# Samba ###################################################
# #########################################################
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    labels:
      - autoheal-mouse=true

    network_mode: host

    environment:
      # --- USERS ---
      ACCOUNT_mouse: ${SAMBA_ACCOUNT_MOUSE}
      UID_mouse: 1101

      ACCOUNT_books: ${SAMBA_ACCOUNT_BOOKS}
      UID_books: 1102

      # --- GROUP ---
      GROUP_sambashare: 1100
      # Add users to group
      GROUPS_mouse: sambashare
      GROUPS_books: sambashare

      # --- SAMBA SETTINGS ---
      SAMBA_CONF_WORKGROUP: WORKGROUP
      SAMBA_CONF_SERVER_STRING: Samba Server
      SAMBA_CONF_SECURITY: user
      SAMBA_CONF_MAP_TO_GUEST: Never
      SAMBA_CONF_LOG_LEVEL: 1

      # --- Security ---
      SAMBA_CONF_SERVER_MIN_PROTOCOL: SMB2
      SAMBA_CONF_SERVER_MAX_PROTOCOL: SMB3
      SAMBA_CONF_SMB_ENCRYPT: required

      # --- SHARE ---
      SAMBA_VOLUME_CONFIG_mouse: |
        [mouse]
        path = /mnt/seagate-red
        browseable = yes
        read only = no
        writable = yes
        valid users = mouse
        force group = sambashare
        create mask = 0664
        directory mask = 0775
        inherit permissions = yes
        oplocks = no
        level2 oplocks = no

      SAMBA_VOLUME_CONFIG_admin_books: |
        [admin_books]
        path = /mnt/seagate-black/library
        browseable = yes
        read only = no
        writable = yes
        valid users = mouse
        force group = sambashare
        create mask = 0664
        directory mask = 0775
        inherit permissions = yes
        oplocks = no
        level2 oplocks = no

      SAMBA_VOLUME_CONFIG_books: |
        [books]
        path = /mnt/seagate-black/library
        browseable = yes
        read only = yes
        writable = no
        valid users = books mouse
        force group = sambashare
        create mask = 0444
        directory mask = 0555
        inherit permissions = yes
        oplocks = no
        level2 oplocks = no

    volumes:
      - /mnt/seagate-red:/mnt/seagate-red
      - /mnt/seagate-black:/mnt/seagate-black

# #########################################################
# Autoheal ###############################################
# #########################################################
  autoheal-mouse:
    image: willfarrell/autoheal:latest
    container_name: autoheal-mouse
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal-mouse
      - AUTOHEAL_INTERVAL=3600
      - AUTOHEAL_START_PERIOD=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# #########################################################
# Gluetun VPN #############################################
# #########################################################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun_mouse
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${ProtonVPN_Private_Key}
      - SERVER_COUNTRIES=Switzerland
      - TZ=Europe/Zurich
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL=25s
      - CONTROL_SERVER=on
      - CONTROL_SERVER_ADDRESS=:8000
    # expose host ports here because other containers share gluetun's network namespace
    ports:
      # web UI (host_port:container_port) - use 8085:8080 (8080 already used by Traefik)
      - "8085:8080"
      # # torrent listening port (TCP/UDP)
      # # unfortunately we can't choose the port. ProtonVPN assigns a random port on each connection, so we need to expose the default torrent port and let the port updater container handle the dynamic forwarding.
      # - "43210:43210"
      # - "43210:43210/udp"
      # mousehole port
      - "5010:5010"
      # gluetun control server
      # - "8000:8000"
    restart: always
    labels:
      - autoheal-mouse=true
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - gluetun-data:/tmp/gluetun
      - ./secrets/gluetun:/gluetun
    networks:
      mouse_network:
        ipv4_address: 172.32.0.2

# #########################################################
# qBitTorrent #############################################
# #########################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_mouse
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1101
      - PGID=1100
      - TZ=Europe/Zurich
      - WEBUI_PORT=8080
      - TORRENTING_PORT=1
    volumes:
      - /mnt/seagate-red/qbittorrent/config:/config
      - /mnt/seagate-red/qbittorrent/downloads:/downloads
    restart: always
    labels:
      - autoheal-mouse=true
    network_mode: "service:gluetun"

# #########################################################
# MouseHole ###############################################
# #########################################################
  mousehole:
    container_name: mousehole
    image: tmmrtn/mousehole:latest
    depends_on:
      gluetun:
        condition: service_healthy
    # ports:
    #   - "5010:5010"
    volumes:
      - mousehole:/srv/mousehole
    network_mode: service:gluetun
    environment:
      - TZ=Europe/Zurich
    restart: always
    labels:
      - autoheal-mouse=true

# #########################################################
# Port Updater ############################################
# #########################################################
  port-updater:
    build: ./port-updater
    container_name: port_updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mouse_network:
        ipv4_address: 172.32.0.3
    depends_on:
      - gluetun
      - qbittorrent
    environment:
      - QBIT_USER=admin
      - QBIT_PASS=${QBIT_PASS}
      - CHECK_INTERVAL=600
      - ZERO_RETRY_INTERVAL=60
      - GLUETUN_AUTH_USER=${GLUETUN_AUTH_USER}
      - GLUETUN_AUTH_PASS=${GLUETUN_AUTH_PASS}
    restart: unless-stopped
    labels:
      - autoheal-mouse=true

# =========================================================
# Networks ================================================
# =========================================================
networks:
  mouse_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1

# =========================================================
# Volumes =================================================
# =========================================================
volumes:
  mousehole:
  gluetun-data: