http:
  routers:
    # Example service on your beefy server
    beefy-service:
      rule: "Host(`service.fastpi.local`) || Host(`service.home.lan`)"
      entryPoints:
        - web
      middlewares:
        - wake-on-demand
      service: beefy-service
    
    # WOL API for internal use
    wol-api:
      rule: "Host(`wol.fastpi.local`)"
      entryPoints:
        - web
      service: wol-api-service

  middlewares:
    wake-on-demand:
      forwardAuth:
        address: "http://nodered:1880/wake-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Wake-Status"

  services:
    beefy-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.102:8080"  # Your beefy server
        healthCheck:
          path: "/health"
          interval: "30s"
          timeout: "5s"
    
    wol-api-service:
      loadBalancer:
        servers:
          - url: "http://wol-api:5000"