api:
  dashboard: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic/dynamic.yaml"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json


# ACME file placeholder (if you decide to enable LetsEncrypt later)
certificatesResolvers:
  myresolver:
    acme:
      email: "you@example.com" # TODO change later
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web