# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# BackdropCarousel ########################################
# #########################################################
  backdrop-carousel:
    build: .
    container_name: backdrop-carousel
    restart: unless-stopped
    environment:
      - PHOTOS_DIR=/photos
    volumes:
      - ./photos:/photos:ro
    networks:
      - traefik_proxy

# =========================================================
# Networks ================================================
# =========================================================
networks:
  traefik_proxy:
    external: true

# =========================================================
# Volumes =================================================
# =========================================================
