# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# PostgreSQL ##############################################
# #########################################################
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresql
    mem_limit: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASS}
    networks:
      - authentik_internal

# #########################################################
# Authentik Server ########################################
# #########################################################
  server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    container_name: authentik-server
    mem_limit: 1g
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
      AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
      ABS_OIDC_CLIENT_ID: ${ABS_OIDC_CLIENT_ID}
      ABS_OIDC_CLIENT_SECRET: ${ABS_OIDC_CLIENT_SECRET}
      PORTAINER_OIDC_CLIENT_ID: ${PORTAINER_OIDC_CLIENT_ID}
      PORTAINER_OIDC_CLIENT_SECRET: ${PORTAINER_OIDC_CLIENT_SECRET}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - ./blueprints:/blueprints/custom:ro
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - authentik_internal
      - traefik_proxy

# #########################################################
# Authentik Worker ########################################
# #########################################################
  worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    container_name: authentik-worker
    mem_limit: 1g
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
      AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
      ABS_OIDC_CLIENT_ID: ${ABS_OIDC_CLIENT_ID}
      ABS_OIDC_CLIENT_SECRET: ${ABS_OIDC_CLIENT_SECRET}
      PORTAINER_OIDC_CLIENT_ID: ${PORTAINER_OIDC_CLIENT_ID}
      PORTAINER_OIDC_CLIENT_SECRET: ${PORTAINER_OIDC_CLIENT_SECRET}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
      - ./blueprints:/blueprints/custom:ro
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - authentik_internal

# =========================================================
# Networks ================================================
# =========================================================
networks:
  authentik_internal:
    driver: bridge
  traefik_proxy:
    external: true

# =========================================================
# Volumes =================================================
# =========================================================
