jenkins:
  nodes:
    - permanent:
        name: "agent1"
        remoteFS: "/home/jenkins/agent"
        labelString: "arm64 docker"
        mode: NORMAL
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              internalDir: "remoting"
            webSocket: true
