jenkins:
  systemMessage: "Jenkins configured with JCasC"
  numExecutors: 2

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "agent1-secret"
              secret: "${readFile:/run/secrets/agent1_secret}"
