# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# DuckDNS #################################################
# #########################################################
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4
    volumes:
      - ./config:/config
    restart: unless-stopped

# =========================================================
# Networks ================================================
# =========================================================


# =========================================================
# Volumes =================================================
# =========================================================

