http:
  address: 0.0.0.0:3000 # web interface
users:
  - name: admin
    password: $SAMPLE.BCRYPT.HASH # in terminal run: htpasswd -nB admin
dns:
  upstream_dns:
    - 192.168.1.1 # Galaxus Router
    - 1.1.1.1  # Cloudflare
    - 9.9.9.9  # Quad9
filtering:
  rewrites:
    - domain: fastpi.homelab
      answer: 192.168.1.2
schema_version: 29
