# #########################################################
# Services ################################################
# #########################################################
services:
# ---------------------------------------------------------
# Cloudflared ---------------------------------------------
# ---------------------------------------------------------
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token-file /run/secrets/cloudflared_tunnel_token --metrics localhost:20241
    restart: always
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:20241", "ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    secrets:
      - cloudflared_tunnel_token

# # ---------------------------------------------------------
# # Cloudflare DDNS Minecraft -------------------------------
# # ---------------------------------------------------------
#   cloudflare-ddns-minecraft:
#     image: oznu/cloudflare-ddns
#     container_name: cloudflare-ddns-minecraft
#     restart: always
#     environment:
#       - API_KEY=${CLOUDFLARE_API_TOKEN}
#       - ZONE=holy-grail.ch
#       - SUBDOMAIN=minecraft
# # ---------------------------------------------------------
# # Cloudflare DDNS VPN -------------------------------------
# # ---------------------------------------------------------
#   cloudflare-ddns-vpn:
#     image: oznu/cloudflare-ddns
#     container_name: cloudflare-ddns-vpn
#     restart: always
#     environment:
#       - API_KEY=${CLOUDFLARE_API_TOKEN}
#       - ZONE=holy-grail.ch
#       - SUBDOMAIN=vpn
# #########################################################
# Network #################################################
# #########################################################
# networks:
# #########################################################
# Volumes #################################################
# #########################################################
# volumes:
# #########################################################
# Configs #################################################
# #########################################################
# configs:
# #########################################################
# Secrets #################################################
# #########################################################
secrets:
  cloudflared_tunnel_token:
    file: ./secrets/tunnel_token.secret