# #########################################################
# Services ################################################
# #########################################################
services:
# ---------------------------------------------------------
# LoyaltyCards --------------------------------------------
# ---------------------------------------------------------
  loyalty-cards:
    image: tomigorn/loyalty-cards:${IMAGE_TAG}
    container_name: loyalty-cards
    mem_limit: 128m
    restart: unless-stopped
    networks:
      - traefik_proxy

# #########################################################
# Networks ################################################
# #########################################################
networks:
  traefik_proxy:
    external: true
