# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# Traefik #################################################
# #########################################################
  traefik:
    image: traefik:latest
    container_name: traefik
    mem_limit: 256m
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
    - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80       # HTTP
      - 443:443     # HTTPS
      - 8080:8080   # Internal — dashboard only, restricted by IPAllowList
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./traefik/letsencrypt:/letsencrypt    # this is hidden from git via .gitignore
      - ./traefik/logs:/var/log/traefik       # this is hidden from git via .gitignore
    networks:
      - traefik_proxy
    dns:
      - 1.1.1.1
      - 8.8.8.8


# # #########################################################
# # whoami ##################################################
# # #########################################################
# # !!! !!!
# # ONLY FOR TESTING PURPOSES - REMOVE IN PRODUCTION !!!
# # !!! !!!
#   whoami:
#     image: containous/whoami
#     container_name: whoami
#     restart: unless-stopped
# #     labels:
# #       labels no longer needed since we're using file-based dynamic configuration
#     networks:
#       - traefik_proxy
# #     # no host ports required: Traefik will route traffic internally


# =========================================================
# Networks ================================================
# =========================================================
networks:
  traefik_proxy:
    external: true

# =========================================================
# Volumes =================================================
# =========================================================

