# #########################################################
# Services ################################################
# #########################################################
services:
# ---------------------------------------------------------
# LoyaltyCards-Sync (Pocketbase) --------------------------
# ---------------------------------------------------------
  loyalty-sync:
    build: .
    image: loyaltycards-sync:local
    container_name: loyalty-sync
    restart: unless-stopped
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_PUBLIC_URL=${PB_PUBLIC_URL}
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - traefik_proxy

# #########################################################
# Networks ################################################
# #########################################################
networks:
  traefik_proxy:
    external: true

# #########################################################
# Volumes #################################################
# #########################################################
volumes:
  pb_data:
