# =========================================================
# Services ================================================
# =========================================================
services:
# #########################################################
# Stonks ##################################################
# #########################################################
  stonks:
    image: stonks:latest
    container_name: stonks
    mem_limit: 512m
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    networks:
      - traefik_proxy

# =========================================================
# Networks ================================================
# =========================================================
networks:
  traefik_proxy:
    external: true

# =========================================================
# Volumes =================================================
# =========================================================
